// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from '@hotwired/stimulus';
import { registerControllers } from 'stimulus-vite-helpers';
import { Autocomplete } from 'stimulus-autocomplete';

const application = Application.start();

// Configure Stimulus development experience
application.debug = false;
window.Stimulus   = application;

application.register('autocomplete', Autocomplete);

const controllers = import.meta.glob('./**/*_controller.js', { eager: true });
registerControllers(application, controllers);
