:concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - default

:scheduler:
  :schedule:
    bookings_rent_end:
      cron: "0 18 * * *"
      class: "OfficeJobs::Bookings::RentEndJob"
